version: '3'
services:
  blue:
    image: kodekloud/webapp-color:v1
    ports:
      - "8081:8080"
    environment:
      - APP_COLOR=blue
  red:
    image: kodekloud/webapp-color:v1
    ports:
      - "8082:8080"
    environment:
      - APP_COLOR=red
  green:
    image: kodekloud/webapp-color:v1
    ports:
      - "8083:8080"
    environment:
      - APP_COLOR=green
  proxy:
    image: nginx-reverse-proxy:v1
    ports:
      - "80:80"
